/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numberserver;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class AppTest {

    @Test public void appResolves() {
        App server = new App();
        assertNotNull("app should have a greeting", server);
    }
}
