/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numberserver;

import numberserver.client.ClientHandlerFactory;
import numberserver.connection.ConnectionListenerConfiguration;
import numberserver.connection.ConnectionListenerFactory;
import numberserver.logging.LoggingAdapter;
import numberserver.logging.LoggingService;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, InterruptedException {
        var loggingAdapter = new LoggingAdapter();
        var loggingService = new LoggingService(loggingAdapter);

        var clientFactory = new ClientHandlerFactory();

        var connectionConfiguration = new ConnectionListenerConfiguration(4000, 5);
        var connectionFactory = new ConnectionListenerFactory(clientFactory, connectionConfiguration);
        var server = new Server(loggingService, connectionFactory);

        server.startServer();
    }
}
